ansible_become_pass: ENC[AES256_GCM,data:sfRABLnIG90=,iv:Pq0H3w08A1mJ9H8UQR3PsgTCzFMoMUUx+LKzNxotxUI=,tag:aUyfrpY6LDqFNKED63HeBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMURrZVdpZDdhaHFmV3Yz
            N0kzeHkrRVFPWWczTVR4S3B0UXpXcWl5VEdRCnlOMjkwZ1hnZ21LU2RCV0xsUFpx
            TDBqZWxVTWYyUkpaZ3R1Y3c0V2RqV0EKLS0tIFBteFZiVGFtaDVmNHFqemVPQmFw
            Q09KR2VkNUR4MGE0ZlZRRWdrRlpsVm8K1Ak8TR8UeTaGfPdfDYCSFz6LZpBOXePb
            C2BBTbBXXZ2cqXb44k/3wcRGYZfVwC2UmZPZaKusw1JZJUacsFx0yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T16:57:38Z"
    mac: ENC[AES256_GCM,data:ECSrK+cuR3KaeASTX+/PFHC2CJZkMGyF9xOSFezgMtePfYhlMJluXh81uxKmKFr+NWm4cJZaDTv5ZiI63pNPA40W1vfmu3F+CT1nRTV7/FOmhBl9c2mdGgsLeLFQx5C6f9giC69vGbeDpK4Ikgjc53ny/zZlQZzFYXfKEcAHKAo=,iv:LTTIkdOCj8GZvBH6snU2fso0+uSll9f8xNEhrTRr6Dk=,tag:7xfZdoCQdTiyu0uh6qIS9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
