ansible_become_pass: ENC[AES256_GCM,data:HHZFWeLwraE=,iv:g6iNi4c5xJCwnkkl6d6Mxo74v+wdopIuKPcFt2asSEs=,tag:WcQG6v51TYRxz+DukPl15A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlg0QnlzbFFCSXJ3dy9Z
            NXlUbW9NcS9VdC9FaGo2aDljak5NenVnSzBvCnl0QXRRSFRnc09CRjZncDFWSFhu
            aUVPVFI2OXdndUhaVXpJOWNjWFRRbnMKLS0tIDlzaTZmVkpEQW5aWUp4N3BNdEx3
            cmtvMHBuNituU1pzVnJNZ21rZmg1Rm8Kxq6XpkhbyQ0QTaEh7vpdDr8tXLtgpnue
            nKeAUUme+3z9kNeS9ZI7pasjM8hfHtkRcaHadlIYZn8QEVjuMDBMkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T23:50:38Z"
    mac: ENC[AES256_GCM,data:Sj6+wMqk3KEM4JjmC8N5FmT3RtDA5pCNqqFJJDCxcLdj3Jw5YtLU35DaRsy6BoFI55h4F+vZkiIynawZe4EI/1sHCpmYmi3jmfRawuJf86aSMCpW/YyD7R3nFJAQRQSfAlu0HPUn9rSnJTX518se/pH71oK9ORBRG9Gn1garPc0=,iv:3n/++VjLuC5RSEdySLpMVp7FEjt5qCyYts9K8chP9kY=,tag:MRYSG2otv26maZLfJXyvCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
