ansible_become_pass: ENC[AES256_GCM,data:3CekSGZyKaI=,iv:gfcNnca/J1TrNfqLT7/uWdDjnewsQwajW14GUTfkOU0=,tag:UpMgcIX/vvEdSEsuVnkt9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eGJiTWtMeUxuNXc3MDRr
            RVY1S0RSd2JwRHdoOGhVcWlKZnlCdVlmeEVnClcwaVNHRjFIU0x1QUpKTThDZitJ
            NmcwUmo4KzNuK1hOUjM4QUFMdjJMQVkKLS0tIFpDNHgyRC8vWmhCZ1VqZzVROGdB
            M1pLVjZZSzBaN1ZiQmdrSStYK1g1NzQKQrFMHcTcD90YQkvF/8j/hLLNsjj7Rjya
            ETyLhwyvEsWmpHsGU+DN52vnkE4WVaGlQfsBfBO89Hrty+R/Ec7S0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T10:28:27Z"
    mac: ENC[AES256_GCM,data:B98dwr8oqRuk1JkdW5Q8I3tTQ2nx0GtxtCEOhIxcgQdu/nBiRB2CvejKbgQsnIPBPfKJVpVUNlThr4mdFKKROS13C0yBlLT714xivBS2GNad6NzM0eFF+iglZxDTa0JpU1ko997dXiTanCTOXDqO4b/a/BqeJdLmFJZVPABrTvM=,iv:dQma0cdPpnR/SdU6E+bTIIGqjKicpx9XxSjW2B/UUUs=,tag:UVi81jnkKu9UE+DISS5R6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
