apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:vNxAST0kub4=,iv:dpbF7vzClThtmzvavausUZ8zI7ZX14vN1Le/vMnNfSY=,tag:nYfrW60Vr0ZfGg4B/lhHsQ==,type:str]
    admin-user: ENC[AES256_GCM,data:b7MBO1o=,iv:uScX1V+B/FMJ7bIFA0eg+JN99T30JxpOE7RzUhBc10E=,tag:fSPqAdGS9HPEnZD/Jio8WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcHExMDhMc0hrSlYxT0Ni
            UWp1cjQzeWNGay9SQ041UXFEdmVzL3hkeDJBCnM2c0ptL3NkclBqQXBnRlhQZEwz
            RzdNQlljSnphSitFa3NwbVRmdld0SHMKLS0tIEZGQk5jNlhNVnpmTngweW42byty
            TFFjei9NSWwyWS9xZ1FuUlhYMGh2UUUK/NdIt9AoEBU7zEF4CWFWHnqskIyYxLaD
            EZ/ew8FAjddC8jDS3QHzjOljcEAtTrIgPXkQTPGfSXQADg6pjgZCOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T10:29:00Z"
    mac: ENC[AES256_GCM,data:7CnFrhnYvm3lZc4TyomVmjcSnfXAl4fsxcUk9ijBtQEOr58HUl8Bbm2c5YVqgyoU51q9xWZ+oPE3duEmEskzKNrxUxTEF4Y19p4m3Vm9j5yLj6QXz20/LvZpFquAPVkVXQXaP6tzL3MPAakE7ee/2rDB6rXV+97zLRiV7PqDj4E=,iv:wSTw64drWGxEP7F0PffrfMCW8GE4CODE35Z1AQwKbaY=,tag:sF0U9BXVf93pHNFgwHzR/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
