---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: unpoller-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_PASS: "{{ .UNPOLLER_PASSWORD }}"
  dataFrom:
    - extract:
        key: /bakerkubes/unifi


