apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:1NPrpM/CmXkYmvt4TQBGau35dA/oQ/x/rH+WXMhV/MCtU0cHKrTDcg==,iv:yt/D/R/bMUoyYkfgA9RIEYXcK5DJHLpfaCCJ6nLz8Bc=,tag:IADq4bEHJZJm0NRhxNgV3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQmozaHluL2ppUy9BNVkz
            eE9ObThKZy9WdE90SHdNbG1zR2RLUVFzeUJ3CmdSUjlFRW9hUU5nSXEybHEyWWVi
            TktoSHo2QnhPT2hwS2Z0d2NERzk3Zm8KLS0tIGs2N2taZ3lQQWlTVm40NWpOaUs1
            NSszNGxUaUNWbnRTZVNtT0VZVXVSTlUKLCHA4hPjEo6eLH8fjjmoDWeDxkBwx0IZ
            49wes+SvfXxl0pWuJX2vIET8cbtz92n6c2WmJ1HdogPvKNxtdXfTGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T10:28:57Z"
    mac: ENC[AES256_GCM,data:HYMHU2qH07/77B5AQUwYGgGucxLsjn8/wW50wE8fZkyqDL2LDBP+eJxsFy83MqcTU3A081uYL9Qlq8IdlDHlgDDhWOpLxjTbAcxJzCv2xj+Nn628gm5m5eder64LghbSmlqX+8X2Ozzimqd+dqHUiiQt8c+Ngxxok5Ko0A7lUjU=,iv:A6ByJwLQ9NOVtOKT0RmbVWqQgITtm+cOqvU7VCXoEto=,tag:PUJlsfFwvPVwHAcw2rvn8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
