apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2oSosfqk5SW/Q93aOPf2UKyrEqwCPy2iGACLreQqtQzKJlV4hR8MhA==,iv:Be11qZEW9v9La2lA26yB2nU0FLFe0UvQdPPFIFdvM/8=,tag:A4b9OtzbkkqqjEypv6zFyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WXo5dXo2R2RsT3VLbDZL
            aVNhWi9PN0lRcXdpWG5LNUVoQU1pMzBiWXo4CnZwYkRRNDMrU21RUHkrNFJPZEV2
            NUFYQWpVWXdqMXdGcUV5eko2SDdRNUEKLS0tIERiVzJ3VnZXT3E1MlNhVUh4bU5W
            bHF0MjVPcWVmWksyenZ0eG1NYktvSE0KmCZDxM6X8hCs43ux2LUrxp6GPLBOGHAp
            ps9o7DGCqTz8xqUWHRg7ZuHxZ2PT9YSXYhg6rHsxbBE9tpWpw03zpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T20:59:50Z"
    mac: ENC[AES256_GCM,data:bzd3M6vVCo3it42fiGdV9WSnnd+VaKknDcG+7Cn8nnfeb1D0i75QpQmaudYNZbYV1iFiF2yM2bmxSMTGffEl0xvM1R+LNMjfnfIcU0HOFhETp4z7//u9IHZn/tX9DGLDhs7PdG6/IY05R6JuN6IEh5tWlv53JS0mZK9lSn9TRuM=,iv:vDZoX1jt1AlvyIjbNBJM9em+7F+Oq0OYh1Q0rADYR/I=,tag:ADHIpGlcmbH8r8NkP8kk0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
