---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-network
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/network
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-fast-kubes
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/fast_disk/kubes
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-films
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/films
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-music
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/music
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-pictures
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/pictures
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-tv
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/tv
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-shared
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/shared
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-server
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_6tb/server
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-downloads
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/fast_disk/downloads
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-s3
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.5
  share: /mnt/sata_16tb/s3
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
