---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: givtcp-config
  namespace: home
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-fast-kubes
