---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shellngn-config
  namespace: networking
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
