---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-network",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static"
            "subnet": "10.0.0.0/22""
            ]
          }
        }
      ]
    }

# "routes": [
#   { "dst": "10.0.0.0/22", "gw": "10.0.0.1" }

