---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-network
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "multus-network",
      "type": "macvlan",
      "master": "eth0",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/22",
      }
    }'
